clase crashlytics
janis-commerce/app-crashlytics pull request #3
Opened 2023-11-13 19:17 UTC by dam788

### LINK DE TICKET:  

https://janiscommerce.atlassian.net/browse/APPSRN-241

### DESCRIPCIÓN DEL REQUERIMIENTO:

**Contexto:**
Al recibir un error en la consola de firebase crashlytics no hay suficiente información del usuario, lo que a veces hace mas difícil reconocer la causa del error o bien cada vez que se utiliza el método tenemos que repetir data innecesariamente

**Necesidad:**
Crear una clase que contenga todo lo mismo de antes, pero que pueda recibir por el constructor data para ser inicializada una sola vez, y aunque se utilice el método log y no le pases data, siempre tenga la data del usuario de forma predeterminada.

### DESCRIPCIÓN DE LA SOLUCIÓN:

- Se creó una clase **Crashlytics** pensando en la ventaja de inicializar la clase una sola vez y poder utilizarla en todo el proyecto. Desde el constructor va a setear userData que espera un **objeto** _(pensando en getUserInfo)_.

- A la clase **Crashlytics** se le agregó los métodos ya existentes:
  - **crahsThisApp**
  - **recordError**
  - **log**

- Se agregaron los test en un solo archivo.

### CÓMO SE PUEDE PROBAR?

- linkee crashlytics con  el comando `yalc push && yalc publish `

- agreguelo en su app con: `yalc add @janiscommerce/app-crashlytics` y `npm i`

- puede armarse una rama de pruebas como [LINK](https://bitbucket.org/fizzmodsrl/janis-wms-app/branch/clase-crashlytics), donde ya se probó el funcionamiento del desarrollo. Si quiere generar pruebas propias debe generar un **google-services.json** nuevo y no lleva mucho tiempo [ LINK](https://firebase.google.com/products/crashlytics?gad=1&gclid=Cj0KCQiAr8eqBhD3ARIsAIe-buPsvzzqEaDy1sL5PbYyjvPgR0g3tb-fAfi1XwAouYQdjliAcOa_-ZgaAkNbEALw_wcB&gclsrc=aw.ds&hl=es-419)

### SCREENSHOTS:

### DATOS EXTRA A TENER EN CUENTA:

2023-11-13 21:23 UTC, GonzaFran commented on lib/index.js
> +  async recordError(error, jsErrorName) {
Según lo conversado, se tiene que agregar un 3er parametro opcional que sean los atributos extra que queremos logear junto a este error

2023-11-13 21:27 UTC, GonzaFran commented on lib/index.js
> +
Según lo conversado, se tiene que agregar la función setAttribute, que se utilizará para darle mayor contexto al error y que, inicialmente, debe tener que enviar la información acumulada en userData. Sumado a esta información, y en caso de que sean validos, se debe agregar la data del objeto recibido como 3er parametro opcional.

Recordar que se debe priorizar los valores de userData por sobre los de los atributos opcionales

2023-11-13 21:28 UTC, GonzaFran commented on lib/index.js
> +    const attributesData = {...this.userData, ...attributes};
Acá invertir el orden en que se destructuran las propiedades para darle prioridad a los valores de userData.

`const attributesData = { ...attributes, ...this.userData}`

2023-11-13 21:29 UTC, GonzaFran requested changes
Se dejaron comentarios en el PR según lo conversado

2023-11-14 23:20 UTC, GonzaFran approved these changes

2023-11-22 16:52 UTC, Maukr reviewed
@dam788 Estuve viendo el package de analytics también un poco, y veo que la estructura de los archivos es un toque diferente.
Por ejemplo, en analytics tienen la clase en un file 'analytics.js' y desde el index lo exportan.
Lo mismo con como se manejan las utils.
Nose si es parte de este desarrollo pero estaría bueno unificar esto

2023-11-22 16:52 UTC, Maukr commented on lib/index.js
> +      ? await setAttributes(attributes[key])
Hola @dam788  parece que  `setAttributes` y `setAttribute` quedaron sin el import

2023-11-23 14:07 UTC, dam788 commented on lib/index.js
> +      ? await setAttributes(attributes[key])
Perfecto, ya estan las correcciones.

2023-11-28 17:13 UTC, Maukr approved these changes

2023-12-05 18:24 UTC, christian97dd requested changes
lo dejo marcado como request changes para organizar una call así podemos refinar un poco mas y dejar las clases crashlytics y analytics similares

2023-12-12 20:27 UTC, christian97dd requested changes
dejo un comentario de una validación, el resto lo ví bien

2023-12-12 20:27 UTC, christian97dd commented on lib/crashlytics.js
> +      if(!!Object.keys(this.userData).length) return null;
acá tenes que validar tambien que userData no sea falsy, haciendo `if (!!this.userData && !!Object.keys(this.userData).length) return null; ` ya queda, si no al hacer un object.keys de un valor falsy, rompe

2023-12-14 20:48 UTC, dam788 commented on lib/crashlytics.js
> +      if(!!Object.keys(this.userData).length) return null;
listo!

2023-12-18 14:08 UTC, merged